SELECT DISTINCT
    PROTOCOL_OBSERVATION_FACT_SV.PATIENT_NUM,
    PROTOCOL_OBSERVATION_FACT_SV.CONCEPT_CD,
    PROTOCOL_OBSERVATION_FACT_SV.TVAL_CHAR,
    PROTOCOL_OBSERVATION_FACT_SV.NVAL_NUM,
    PROTOCOL_OBSERVATION_FACT_SV.START_DATE
FROM PROTOCOL_OBSERVATION_FACT_SV
WHERE
    STARTSWITH(PROTOCOL_OBSERVATION_FACT_SV.CONCEPT_CD, 'LAB:')
    AND PATIENT_NUM IN (%s);