WITH 
MATCHING_CONCEPTS AS (
    SELECT CONCEPT_CD
    FROM CONCEPT_DIMENSION
    WHERE
        STARTSWITH (CONCEPT_CD, 'ICD10:G44')
        OR STARTSWITH (CONCEPT_CD, 'ICD10:R51')
        OR STARTSWITH (CONCEPT_CD, 'ICD10:G93.2')
        OR STARTSWITH (CONCEPT_CD, 'ICD10:H47.1')
),
CPT_CODES AS (
    SELECT CONCEPT_CD
    FROM CONCEPT_DIMENSION
    WHERE STARTSWITH(CONCEPT_CD, 'CPT4:62')
),
FILTERED_CPT_CODES AS (
    SELECT CONCEPT_CD
    FROM CPT_CODES
    WHERE
        TO_NUMBER(REPLACE(CONCEPT_CD, 'CPT4:', '')) > 62262 
        AND TO_NUMBER(REPLACE(CONCEPT_CD, 'CPT4:', '')) < 62330
),
COMBINED_CONCEPTS AS (
    SELECT CONCEPT_CD FROM FILTERED_CPT_CODES 
    UNION 
    SELECT CONCEPT_CD FROM MATCHING_CONCEPTS
)

SELECT PATIENT_NUM, COMBINED_CONCEPTS.CONCEPT_CD, START_DATE
FROM PROTOCOL_OBSERVATION_FACT_SV
INNER JOIN COMBINED_CONCEPTS ON COMBINED_CONCEPTS.CONCEPT_CD = PROTOCOL_OBSERVATION_FACT_SV.CONCEPT_CD
WHERE REPLACE(PATIENT_NUM, '.00000', '') IN (%s);